Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2020-08, with the labels that each got.

#77 ADAPT-554 Updated mobile navigation styles
  dist/assets/svg/caret-down-white.svg
  dist/css/components.css
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs

#75 ADAPT-551: Initial setup for mobile-only label.
  dist/css/components.css
  src/scss/components/wysiwyg/_table.scss
Labels: size/xs

#78 Adapt 551 table label
  dist/css/components.css
  src/scss/components/wysiwyg/_table.scss
Labels: size/xs

#76 ADAPT-451 Clean up React Widget
  src/associates/lib/app.bundle.js
  src/associates/lib/main.css
  src/associates/src/components/newMembers/NewMembers.jsx
  src/associates/src/components/newMembers/newMembers.css
  src/associates/src/saa-scss/saa-associates.scss
  templates/node--61.html.twig
Labels: size/xs

#80 ADAPT-000: Removed underline on cta and other icon links.
  dist/css/theme.css
  src/scss/theme/_cta.scss
Labels: size/xs

#74 Adapt 443 fat footer
  dist/assets/svg/saa-logo-color.svg
  dist/css/saa-victoria.css
  saa-logo.svg
  src/assets/svg/saa-logo-color.svg
  src/scss/components/fat-footer/_footer--column-one.scss
  src/scss/components/fat-footer/_footer--links-buttons.scss
  src/scss/components/fat-footer/_footer.scss
  src/scss/components/fat-footer/index.scss
  src/scss/components/index.scss
  src/scss/theme/_footer.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_footer-links.scss
  src/scss/utilities/mixins/index.scss
  src/scss/utilities/mixins/typography/_font-sizes--between-modular-typography.scss
  templates/components/fat-footer/saa-fat-footer.html.twig
  templates/page.html.twig
  test.txt
Labels: size/m

#81 Adapt 443 fat footer
  templates/components/fat-footer/saa-fat-footer.html.twig
Labels: size/xs

#82 Adapt 443 fat footer Checking Issues
  src/scss/components/fat-footer/_footer.scss
  templates/components/fat-footer/saa-fat-footer.html.twig
  templates/page.html.twig
Labels: size/xs

#83 Adapt 443 fat footer
  dist/assets/svg/saa-logo-color.svg
  dist/css/saa-victoria.css
  src/assets/svg/saa-logo-color.svg
  src/scss/components/fat-footer/_footer--column-one.scss
  src/scss/components/fat-footer/_footer.scss
  templates/components/fat-footer/saa-fat-footer.html.twig
Labels: size/s

#86 ADAPT-000: Removed red underline for regular links not hovered on.
  dist/css/saa-victoria.css
  src/scss/theme/_cta.scss
Labels: size/xs

#84 ADAPT-477 Fixed Big Button Mixin issue
  dist/css/saa-victoria.css
  src/scss/utilities/mixins/_buttons.scss
Labels: size/xs

#85 ADAPT-564 Updated React Widget message when browser is not compatible
  templates/node--61.html.twig
Labels: size/xs

#79 ADAPT-559 Reorganized file structure for cards and resolved line-height issue
  dist/css/saa-victoria.css
  src/scss/components/card/_card.scss
  src/scss/components/card/faux-cards/_faux-card--bordered-list.scss
  src/scss/components/card/faux-cards/_faux-card--cta-list.scss
  src/scss/components/card/faux-cards/_faux-card--fonts.scss
  src/scss/components/card/faux-cards/_faux-card--horizontal-general.scss
  src/scss/components/card/faux-cards/_faux-card--horizontal-min-circle.scss
  src/scss/components/card/faux-cards/_faux-card--horizontal-min-square.scss
  src/scss/components/card/faux-cards/_faux-card--layout--media-text-area.scss
  src/scss/components/card/faux-cards/_faux-card--vertical-general.scss
  src/scss/components/card/faux-cards/_media-caption-text-area-layout.scss
  src/scss/components/card/faux-cards/index.scss
  src/scss/components/card/icon-cards/_icon-card.scss
  src/scss/components/card/icon-cards/index.scss
  src/scss/components/card/index.scss
  src/scss/components/index.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/theme/icon-cards/_icon-card--single-in-row.scss
  src/scss/theme/index.scss
Labels: size/xs

#87 Adapt 554 external link icons
  dist/css/saa-victoria.css
  src/scss/theme/_button.scss
  src/scss/theme/icon-cards/_icon-card--single-in-row.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_cta.scss
Labels: size/xs

#88 ADAPT-554: Adjusting buttons to set icon color.
  dist/css/saa-victoria.css
  src/scss/utilities/mixins/_cta.scss
Labels: size/xs

#89 ADAPT-639: First pass at adding link underline back in for regular li…
  dist/css/saa-victoria.css
  src/scss/utilities/mixins/_cta.scss
Labels: size/xs

#90 ADAPT-552: Adjusted smaller mobile spacing for cards, faux cards, pag…
  dist/css/saa-victoria.css
  src/scss/components/card/faux-cards/_faux-card--bordered-list.scss
  src/scss/components/card/faux-cards/_faux-card--cta-list.scss
  src/scss/components/card/faux-cards/_faux-card--fonts.scss
  src/scss/components/card/faux-cards/_faux-card--layout--media-text-area.scss
  src/scss/components/card/faux-cards/_faux-card--vertical-general.scss
  src/scss/components/card/icon-cards/_icon-card.scss
  src/scss/components/index.scss
  src/scss/components/paragraphs/_react-paragraph--general.scss
  src/scss/components/paragraphs/index.scss
  src/scss/theme/_mobile-spacing--general.scss
  src/scss/theme/index.scss
  src/scss/utilities/variables/_mobile-modular-spacing.scss
  src/scss/utilities/variables/index.scss
Labels: size/s

#91 Adapt 552 mobile spacing v3
  dist/css/saa-victoria.css
  src/scss/components/card/faux-cards/_faux-card--layout--media-text-area.scss
  src/scss/components/paragraphs/_react-paragraph--general.scss
  src/scss/utilities/variables/_mobile-modular-spacing.scss
Labels: size/xs

#92 ADAPT-623: Pre-launch changes to Fat Footer
  templates/components/fat-footer/saa-fat-footer.html.twig
Labels: size/xs
