Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2020-07, with the labels that each got.

#30 ADAPT-454 Hide masthead theme appearance settings
  theme-settings.php
Labels: size/xs

#26 ADAPT-398 Hardcode Associates React App to a specific node
  saa_victoria_subtheme.libraries.yml
  src/associates/.babelrc
  src/associates/.gitignore
  src/associates/README.md
  src/associates/index.html
  src/associates/lib/app.bundle.js
  src/associates/lib/main.css
  src/associates/package-lock.json
  src/associates/package.json
  src/associates/src/components/App.jsx
  src/associates/src/components/app.css
  src/associates/src/components/counter/Counter.jsx
  src/associates/src/components/letter/Letter.jsx
  src/associates/src/components/letter/letter.css
  src/associates/src/components/nameTabs/NameTabs.jsx
  src/associates/src/components/nameTabs/nameTabs.css
  src/associates/src/components/newMembers/NewMembers.jsx
  src/associates/src/components/newMembers/newMembers.css
  src/associates/src/components/search/Search.jsx
  src/associates/src/components/search/search.css
  src/associates/src/components/searchResults/SearchResults.jsx
  src/associates/src/components/searchResults/searchResults.css
  src/associates/src/index.js
  src/associates/src/saa-scss/saa-associates.scss
  src/associates/webpack.config.js
  templates/node--20.html.twig
Labels: size/xl

#29 Adapt 381 faux cards cleanup
  dist/css/theme.css
  src/scss/theme/_button.scss
  src/scss/theme/_cta.scss
  src/scss/theme/faux-cards/_faux-card--fonts.scss
  src/scss/theme/faux-cards/_faux-card--horizontal-general.scss
  src/scss/theme/faux-cards/_faux-card--horizontal-min-circle.scss
  src/scss/theme/faux-cards/_faux-card--horizontal-min-square.scss
  src/scss/theme/faux-cards/_faux-card--layout--media-text-area.scss
  src/scss/theme/faux-cards/_faux-card--vertical-general.scss
  src/scss/theme/faux-cards/_media-caption-text-area-layout.scss
  src/scss/theme/faux-cards/index.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_buttons.scss
Labels: size/s

#28 ADAPT-378 Style global brand bar and masthead with logo
  dist/assets/svg/icon-search.svg
  dist/css/components.css
  dist/css/theme.css
  saa-logo.svg
  saa_victoria_subtheme.theme
  src/assets/svg/icon-search.svg
  src/scss/components/brand-bar/_brand-bar.scss
  src/scss/components/brand-bar/index.scss
  src/scss/components/index.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/components/lockup/index.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/components/main-nav/index.scss
  src/scss/components/search-bar/_search-bar.scss
  src/scss/components/search-bar/index.scss
  src/scss/utilities/variables/_colors.scss
  templates/components/brand-bar/saa--brand-bar.html.twig
  templates/components/lockup/saa--lockup.html.twig
  templates/page.html.twig
  test.txt
Labels: size/s

#33 Adapt 468 list cards
  dist/css/theme.css
  src/scss/theme/faux-cards/_faux-card--bordered-list.scss
  src/scss/theme/faux-cards/_faux-card--cta-list.scss
  src/scss/theme/faux-cards/index.scss
Labels: size/xs

#36 ADAPT-000: Fix ul ol style with tailwind override file.
  dist/css/base.css
  src/scss/base/_tailwind-overrides.scss
  src/scss/base/index.scss
Labels: size/xs

#37 ADAPT-000: Fixed bad color definition that was not necessary.
  dist/css/theme.css
  src/scss/utilities/variables/_colors.scss
Labels: size/xs

#34 ADAPT-453 Fix button and cta link styles
  dist/css/theme.css
  src/scss/theme/_cta.scss
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/mixins/_top-banner.scss
Labels: size/s

#38 ADAPT-000 Updated location of brand-bar logo
  src/assets/svg/saa-logo.svg
  templates/components/brand-bar/saa--brand-bar.html.twig
Labels: size/xs

#39 ADAPT-476: Added Victoria screenshot for the theme.
  screenshot.png
Labels: size/xs

#41 ADAPT-476: Rebuilt and committed saa-logo in dist folder.
  dist/assets/svg/saa-logo.svg
  templates/components/brand-bar/saa--brand-bar.html.twig
Labels: size/s

#42 ADAPT-476: Added base input style fix.
  dist/css/base.css
  src/scss/base/_tailwind-overrides.scss
Labels: size/xs

#43 Adapt 476 big secondary button
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_top-banner.scss
Labels: size/xs

#44 Update page.html.twig
  templates/page.html.twig
  test.txt
Labels: size/xs

#45 Adapt 476 small horizontal card alignment
  dist/css/theme.css
  src/scss/theme/faux-cards/_faux-card--horizontal-min-circle.scss
Labels: size/xs

#46 ADAPT-000 Update brand bar logo destination
  templates/components/brand-bar/saa--brand-bar.html.twig
Labels: size/xs

#47 ADAPT-000 Update brand bar height and logo position
  dist/css/components.css
  src/scss/components/brand-bar/_brand-bar.scss
Labels: size/xs

#48 ADAPT-476: Adjusted banner h2 to be bigger.
  dist/css/theme.css
  src/scss/utilities/mixins/_top-banner.scss
Labels: size/xs

#49 ADAPT-000 Update vivid red variables to use SAA's vivid red
  dist/css/components.css
  dist/css/theme.css
  src/scss/base/fonts/_header-links.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/theme/_cta.scss
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/variables/_colors.scss
Labels: size/xs

#52 ADAPT-482 Update lockup line height for specific breakpoints
  dist/css/components.css
  src/scss/components/lockup/_lockup.scss
Labels: size/xs

#51 Adapt 476 sidebar nav
  dist/css/components.css
  src/scss/components/index.scss
  src/scss/components/side-nav/_side-nav.scss
  src/scss/components/side-nav/index.scss
Labels: size/xs

#50 Adapt 476 single card font sizes
  dist/css/components.css
  dist/css/theme.css
  src/scss/theme/icon-cards/_icon-card--single-in-row.scss
  src/scss/theme/icon-cards/_icon-card.scss
  src/scss/theme/icon-cards/index.scss
  src/scss/theme/index.scss
Labels: size/xs

#53 ADAPT-476: Fixed special case of stronger button hover color style.
  dist/css/theme.css
  src/scss/theme/_button.scss
Labels: size/xs

#54 ADAPT-476: Adjusted selector for media precedes the card contents
  dist/css/theme.css
  src/scss/theme/icon-cards/_icon-card.scss
Labels: size/xs

#55 ADAPT-000: Added 1em padding to match stanford basic.
  dist/css/base.css
  src/scss/base/_tailwind-overrides.scss
Labels: size/xs

#56 ADAPT-476 Added lockup link to home page
  templates/components/lockup/saa--lockup.html.twig
Labels: size/xs

#57 ADAPT-476 Fixed nav hover issue
  dist/css/components.css
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs

#59 ADAPT-000: Added smaller max-width for testimonial banner on sidebar …
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--testimonial-image-and-text.scss
Labels: size/xs

#58 ADAPT-515 Updated user login page to use ADAPT branding and colors
  dist/css/theme.css
  src/scss/theme/_button.scss
  src/scss/theme/_user-login.scss
  src/scss/theme/index.scss
  templates/page--user--login.html.twig
Labels: size/xs

#60 Create pull_request_template.md
  pull_request_template.md
Labels: size/xs

#61 ADAPT-000: Removed new file and edited the pull request template in t…
  .github/pull_request_template.md
  pull_request_template.md
Labels: size/xs

#63 ADAPT-481: Adjusting margin on top of tables after headings.
  dist/css/components.css
  src/scss/components/wysiwyg/_table.scss
Labels: size/xs

#64 Adapt 526 style requests
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/theme/_cta.scss
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/theme/icon-cards/_icon-card.scss
Labels: size/xs

#62 ADAPT-525 Fixed heading 1, testimonial padding-bottom, and changed svg to png
  dist/assets/png/saa-logo.png
  dist/assets/svg/saa-logo.svg
  dist/css/base.css
  dist/css/theme.css
  src/assets/png/saa-logo.png
  src/assets/svg/saa-logo.svg
  src/scss/base/fonts/_base-fonts.scss
  src/scss/theme/banners/_banner-in-page--testimonial-image-and-text.scss
  templates/components/brand-bar/saa--brand-bar.html.twig
Labels: size/s

#65 ADAPT-526: Added mixin for small text size and fixed vivid red banner…
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/theme/faux-cards/_faux-card--fonts.scss
  src/scss/utilities/mixins/typography/_font-sizes--between-modular-typography.scss
  src/scss/utilities/mixins/typography/index.scss
Labels: size/xs

#66 ADAPT-000: Added lower alpha and roman icons for ordered lists.
  dist/css/base.css
  src/scss/base/_tailwind-overrides.scss
Labels: size/xs

#67 ADAPT-456: Started check mark paragraph styles.
  dist/assets/svg/check.svg
  dist/css/components.css
  src/assets/svg/check.svg
  src/scss/components/wysiwyg/_check-mark-paragraphs.scss
  src/scss/components/wysiwyg/index.scss
Labels: size/xs

#68 Adapt 000 ol styles
  dist/css/base.css
  dist/css/components.css
  src/scss/base/_tailwind-overrides.scss
  src/scss/components/wysiwyg/_lists.scss
  src/scss/components/wysiwyg/index.scss
Labels: size/xs

#69 Adapt 530 vivid red banner links
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/variables/_colors.scss
Labels: size/xs

#70 ADAPT-000 Renamed list class styles to align with css docs
  dist/css/components.css
  src/scss/components/wysiwyg/_lists.scss
Labels: size/xs

#71 ADAPT-530: Fixed glitch for underline on red banner button.
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--no-image.scss
Labels: size/xs

#72 ADAPT-000: Added technical notes about the subtheme.
  README.md
Labels: size/xs
