Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2020-10, with the labels that each got.

#123 ADAPT-885: Updated decanter version.
  package-lock.json
  package.json
Labels: size/m

#124 ADAPT-894: Updated theme version for release.
  saa_victoria_subtheme.info.yml
Labels: size/xs

#125 ADAPT-890: Set theme to be on 1.2 dev version now for improvements.
  saa_victoria_subtheme.info.yml
Labels: size/xs

#106 Adapt 687 improve template inheritance
  templates/node--61.html.twig
  templates/page--user--login.html.twig
  templates/page.html.twig
Labels: size/xs

#126 Update change-branch.php
  dev/change-branch.php
Labels: size/xs

#127 Adapt 884 logo files update
  README.md
  dist/assets/svg/saa-logo-color.svg
  dist/assets/svg/saa-logo-white.svg
  dist/templates/decanter/components/accordion/accordion.twig
  dist/templates/decanter/components/alert/alert.twig
  dist/templates/decanter/components/brand-bar/brand-bar.twig
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/main-nav/main-nav.twig
  dist/templates/decanter/components/media/media.twig
  dist/templates/decanter/components/quote/quote.twig
  dist/templates/decanter/components/site-search/site-search.twig
  src/assets/svg/saa-logo-color.svg
  src/assets/svg/saa-logo-white.svg
Labels: size/l
