Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2020-06, with the labels that each got.

#4 Adapt 286 buttons & cta styles
  dist/css/theme.css
  src/scss/theme/_button.scss
  src/scss/theme/_cta.scss
  src/scss/theme/index.scss
  src/scss/utilities/index.scss
  src/scss/utilities/variables/_colors.scss
  tailwind.config.js
Labels: size/xl

#3 Adapt 284 icon card styles with colored tabs
  README.md
  dist/css/theme.css
  saa_victoria_subtheme.theme
  src/scss/base/_tailwind--modular-spacing--margin.scss
  src/scss/base/_tailwind--modular-spacing--padding.scss
  src/scss/base/_tailwind.scss
  src/scss/base/index.scss
  src/scss/config/index.scss
  src/scss/layout/index.scss
  src/scss/print/index.scss
  src/scss/state/index.scss
  src/scss/theme/_card.scss
  src/scss/theme/_icon-card.scss
  src/scss/theme/_link_classes.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/index.scss
  src/scss/utilities/mixins/typography/_type-a.scss
  src/scss/utilities/mixins/typography/index.scss
  src/scss/utilities/variables/_colors.scss
  src/scss/utilities/variables/index.scss
  templates/components/pattern-card.html.twig
Labels: size/m

#5 ADAPT-284: Fixed color variable values.
  dist/css/theme.css
  tailwind.config.js
Labels: size/xs

#6 Adapt 357 banner options
  dist/css/theme.css
  saa_victoria_subtheme.theme
  src/scss/theme/_button.scss
  src/scss/theme/banners/_banner--in-page-content.scss
  src/scss/theme/banners/_top-banner.scss
  src/scss/theme/banners/index.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_buttons.scss
Labels: size/m

#7 Adapt 349 fonts
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/base/fonts/index.scss
  src/scss/base/index.scss
  src/scss/theme/_icon-card.scss
  src/scss/utilities/mixins/typography/_font-families.scss
  src/scss/utilities/mixins/typography/index.scss
Labels: size/xl

#8 Adapt 286 more button additions
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/img/alert-error.png
  dist/assets/img/alert-info.png
  dist/assets/img/alert-success.png
  dist/assets/img/alert-warning.png
  dist/assets/img/arrow-down.png
  dist/assets/img/check.png
  dist/assets/svg/alert-error.svg
  dist/assets/svg/alert-info.svg
  dist/assets/svg/alert-success.svg
  dist/assets/svg/alert-warning.svg
  dist/assets/svg/arrow-down.svg
  dist/assets/svg/arrow-right.svg
  dist/assets/svg/arrow-up-right.svg
  dist/assets/svg/caret-down-black.svg
  dist/assets/svg/caret-down-white.svg
  dist/assets/svg/caret-down.svg
  dist/assets/svg/caret-right.svg
  dist/assets/svg/check.svg
  dist/assets/svg/close-black.svg
  dist/assets/svg/close-white.svg
  dist/assets/svg/download.svg
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/hamburger-black.svg
  dist/assets/svg/hamburger-white.svg
  dist/assets/svg/icon-search.svg
  dist/assets/svg/lock-solid.svg
  dist/assets/svg/lock.svg
  dist/assets/svg/minus-black.svg
  dist/assets/svg/minus-white.svg
  dist/assets/svg/plus-black.svg
  dist/assets/svg/plus-white.svg
  dist/assets/svg/video.svg
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/index.scss
  src/scss/theme/_cta.scss
  src/scss/utilities/index.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/mixins/index.scss
Labels: size/xl

#9 Adapt 363 reorganizing banner files
  saa_victoria_subtheme.theme
  src/scss/theme/banners/_top-banner--image-and-text.scss
  src/scss/theme/banners/_top-banner--image-only.scss
  src/scss/theme/banners/_top-banner--no-image.scss
  src/scss/theme/banners/index.scss
Labels: size/xs

#10 ADAPT-363: Split out in page banner files.
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/theme/banners/_banner-in-page--testimonial-image-and-text.scss
  src/scss/theme/banners/index.scss
Labels: size/xs

#11 Adapt 367 top banner no image & with image - both red backgrounds
  dist/css/theme.css
  src/scss/theme/_button.scss
  src/scss/theme/banners/_top-banner--image-and-text.scss
  src/scss/theme/banners/_top-banner--no-image.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_top-banner.scss
  src/scss/utilities/mixins/index.scss
Labels: size/s

#15 Adapt 366 fixing style inheritance
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/base/fonts/_header-links.scss
  src/scss/theme/_button.scss
  src/scss/theme/_cta.scss
  src/scss/theme/_icon-card.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_top-banner.scss
  src/scss/utilities/variables/_box-shadows.scss
  src/scss/utilities/variables/index.scss
Labels: size/xl

#12 Adapt 380 special font styles
  dist/css/base.css
  dist/css/theme.css
  saa_victoria_subtheme.libraries.yml
  src/scss/theme/_icon-card.scss
  src/scss/utilities/mixins/typography/_font-families.scss
Labels: size/xs

#13 ADAPT-363 Styled centered vivid red banner
  .idea/workspace.xml
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/utilities/variables/_sizes.scss
  src/scss/utilities/variables/index.scss
Labels: size/s

#16 Adapt 366 tailwind inclusion
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/_tailwind.scss
  src/scss/base/fonts/_base-fonts.scss
  src/scss/base/index.scss
  src/scss/utilities/mixins/typography/_font-families.scss
  tailwind.config.js
Labels: size/s

#17 Adapt 000 small fixes
  dist/css/base.css
  dist/css/theme.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/base/fonts/_header-links.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_top-banner.scss
  src/scss/utilities/variables/_box-shadows.scss
Labels: size/xs

#18 ADAPT-362 Set aspect-ratio for image-only top banner
  dist/css/base.css
  dist/css/components.css
  dist/css/layout.css
  dist/css/print.css
  dist/css/state.css
  dist/css/theme.css
  dist/js/scripts.js
  src/scss/theme/banners/_top-banner--image-only.scss
Labels: size/xl

#19 ADAPT-000 Fixed banner and removed .idea/ folder
  .gitignore
  .idea/workspace.xml
  dist/css/theme.css
  src/scss/theme/banners/_top-banner--image-only.scss
Labels: size/s

#14 ADAPT-364 Style the Testimonial Banner
  dist/css/theme.css
  saa_victoria_subtheme.theme
  src/scss/theme/banners/_banner-in-page--testimonial-image-and-text.scss
  src/scss/utilities/variables/_colors.scss
Labels: size/s

#20 ADAPT-379 Style text area paragraph table
  dist/css/components.css
  src/scss/components/index.scss
  src/scss/components/wysiwyg/_table.scss
  src/scss/components/wysiwyg/index.scss
  src/scss/theme/index.scss
  src/scss/utilities/variables/_colors.scss
Labels: size/xs

#21 ADAPT-389 Change main navigation to be left-aligned
  templates/menu/menu--main.html.twig
Labels: size/xs

#24 Adapt 000 fixing card contents
  dist/css/base.css
  dist/css/components.css
  dist/css/layout.css
  dist/css/print.css
  dist/css/state.css
  dist/css/theme.css
  dist/js/scripts.js
  src/scss/base/fonts/_base-fonts.scss
Labels: size/xl

#23 Adapt 401 buttons cta color updates & footer buttons & CTA
  dist/css/base.css
  dist/css/components.css
  dist/css/layout.css
  dist/css/print.css
  dist/css/state.css
  dist/css/theme.css
  dist/js/scripts.js
  src/scss/theme/_button.scss
  src/scss/theme/_cta.scss
  src/scss/theme/_footer.scss
  src/scss/theme/banners/_banner-in-page--no-image.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/mixins/_top-banner.scss
  src/scss/utilities/variables/_colors.scss
Labels: size/xl

#22 ADAPT-425 Add mobile styling for Banners
  dist/css/theme.css
  src/scss/theme/banners/_banner-in-page--testimonial-image-and-text.scss
  src/scss/theme/banners/_top-banner--image-and-text.scss
Labels: size/xs
