Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2021-02, with the labels that each got.

#138 Update theme version number
  saa_victoria_subtheme.info.yml
Labels: size/xs

#139 Adapt 1679 event & news: SAA color styles
  dist/css/saa-victoria.css
  saa_victoria_subtheme.info.yml
  src/scss/components/events/event-list-items.scss
  src/scss/components/events/event-list-pages.scss
  src/scss/components/events/index.scss
  src/scss/components/index.scss
  src/scss/components/news/index.scss
  src/scss/components/news/news-list-items.scss
  src/scss/components/news/news-list-pages.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/mixins/index.scss
  src/scss/utilities/mixins/list-pages.scss
Labels: size/s

#141 Adapt 1679 event page h1
  dist/css/saa-victoria.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/components/events/event-list-pages.scss
  src/scss/utilities/mixins/typography/_headings.scss
  src/scss/utilities/mixins/typography/index.scss
Labels: size/xs

#140 Updating theme version
  saa_victoria_subtheme.info.yml
Labels: size/xs

#143 Adapt 1194 paragraph behaviors base
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
Labels: size/s

#144 ADAPT-1858: D9 compatibility in theme info file
  dist/templates/decanter/components/local-footer/local-footer.twig
  saa_victoria_subtheme.info.yml
  templates/components/fat-footer/saa-fat-footer.html.twig
Labels: size/xs

#146 ADAPT-1862: Updated theme info to new dev version
  saa_victoria_subtheme.info.yml
Labels: size/xs

#145 Adapt 1195 icon cards variant
  dist/css/saa-victoria.css
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
  src/scss/components/card/icon-cards/_icon-card.scss
  templates/components/pattern-card.html.twig
Labels: size/s

#142 ADAPT-1539: Start of release automation.
  .github/pull_request_template.md
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  dev/bump-yaml.js
  dist/css/saa-victoria.css
  dist/templates/decanter/components/media/media.twig
  package-lock.json
  package.json
  saa_victoria_subtheme.info.yml
  test.txt
Labels: patch, size/xl

#147 Update release.yml
  .github/workflows/release.yml
Labels: size/xs
