Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2021-11, with the labels that each got.

#205 D8CORE-4802 D8CORE-4823
  dist/css/saa-victoria.css
  dist/js/scripts.js
  dist/templates/decanter/components/global-footer/global-footer.twig
  package-lock.json
  package.json
Labels: size/xl

#209 ADAPT-4027: Change font to source sasnce pro for headings
  dist/css/saa-victoria.css
  src/scss/base/fonts/_base-fonts.scss
  src/scss/components/card/icon-card/_icon-card.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/utilities/mixins/typography/_headings.scss
Labels: size/xs

#208 ADAPT-3997 Update 2.x with recent 1.x changes
  package-lock.json
  package.json
  saa_victoria_subtheme.info.yml
  templates/components/fat-footer/saa-fat-footer.html.twig
Labels: size/xs, patch

#214 ADAPT-4070: Restore js for Algolia Search Header
  saa_victoria_subtheme.info.yml
Labels: size/xs, patch
