Repository SU-SWS/saa_victoria_subtheme, pull requests merged in 2021-04, with the labels that each got.

#163 Adapt 1910 horizontal rectangle cards
  dist/css/saa-victoria.css
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
  src/scss/components/card/horizontal-card/_horizontal-card--large-rectangle.scss
  src/scss/components/card/horizontal-card/_horizontal-card--small-circle.scss
  src/scss/components/card/horizontal-card/_horizontal-card-general.scss
  src/scss/components/card/horizontal-card/index.scss
Labels: size/s

#164 ADAPT-2037: Adjusting spacing in horizontal circle card with border.
  dist/css/saa-victoria.css
  src/scss/components/card/horizontal-card/_horizontal-card--small-circle.scss
Labels: size/xs

#165 ADAPT-2038: Adjusted padding inside with border.
  dist/css/saa-victoria.css
  src/scss/components/card/horizontal-card/_horizontal-card--large-rectangle.scss
Labels: size/xs

#162 ADAPT-2035: adding condition for the image classes on cards
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
Labels: size/xs

#168 Adapt 2075 scoping paragraph card styles
  dist/css/saa-victoria.css
  src/scss/components/card/horizontal-card/_horizontal-card--large-rectangle.scss
  src/scss/components/card/horizontal-card/_horizontal-card--small-circle.scss
  src/scss/components/card/horizontal-card/_horizontal-card-general.scss
  src/scss/components/card/icon-card/_icon-card.scss
  src/scss/components/card/vertical-card/_vertical-card-general.scss
Labels: size/s

#166 Adapt 2046 theme function Code improvements
  saa_victoria_subtheme.theme
Labels: size/s

#169 ADAPT-2297 Update version number within saa_victoria_subtheme.info.yml
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#170 ADAPT-2300 Updated version to 8.1.18-dev
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#171 ADAPT-1900: Adjusted circle width during testing with Alison.
  dist/css/saa-victoria.css
  src/scss/components/card/horizontal-card/_horizontal-card--small-circle.scss
Labels: size/xs

#172 Adapt 1900 banner paragraphs
  dist/css/saa-victoria.css
  src/scss/components/banners/_banner--general.scss
  src/scss/components/banners/index.scss
Labels: size/l

#167 Paragraph variants 2021
  dist/css/saa-victoria.css
  dist/templates/decanter/components/card/card.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
  src/scss/components/banners/_banner--general.scss
  src/scss/components/banners/index.scss
  src/scss/components/card/_card.scss
  src/scss/components/card/_minimal-border.scss
  src/scss/components/card/horizontal-card/_horizontal-card--large-rectangle.scss
  src/scss/components/card/horizontal-card/_horizontal-card--small-circle.scss
  src/scss/components/card/horizontal-card/_horizontal-card-general.scss
  src/scss/components/card/horizontal-card/index.scss
  src/scss/components/card/icon-card/_icon-card.scss
  src/scss/components/card/icon-card/index.scss
  src/scss/components/card/icon-cards/_icon-card.scss
  src/scss/components/card/index.scss
  src/scss/components/card/vertical-card/_vertical-card-general.scss
  src/scss/components/card/vertical-card/index.scss
  templates/components/pattern-card.html.twig
Labels: size/l

#173 ADAPT-1967: Upped theme info version for release
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#174 Setting back to dev version for next tickets
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#175 ADAPT-2325 Resolve mobile spacing for icon cards
  dist/css/saa-victoria.css
  src/scss/components/card/icon-card/_icon-card.scss
Labels: size/xs

#176 ADAPT-2337 Update version for Icon Card fix release
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#177 ADAPT-2339 Incremented version number for dev
  saa_victoria_subtheme.info.yml
Labels: patch, size/xs

#178 ADAPT-1913 Created List Style field options for Card Variants
  dist/css/saa-victoria.css
  dist/templates/decanter/components/card/card.twig
  saa_victoria_subtheme.react_behaviors.yml
  saa_victoria_subtheme.theme
  src/scss/components/card/_card-list.scss
  src/scss/components/card/index.scss
Labels: size/xs
